<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class StudentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            ['nrp' => 'M2101001','name' => 'Arrumaisha Ghaida Puspitasari','class' => 'XI.IPS-2','division' => 'MM','gen' => 18,'created_at' => now()],
            ['nrp' => 'M2101002','name' => 'Daffa Pati Arya ','class' => 'XI.IPS-3','division' => 'MM','gen' => 18,'created_at' => now()],
            ['nrp' => 'M2101017','name' => 'Farras Rajilmahasin ','class' => 'XI.U.A-5','division' => 'MM','gen' => 18,'created_at' => now()],
            ['nrp' => 'M2101005','name' => 'Kamila Rannya Azzahra ','class' => 'XI.IPS-1','division' => 'MM','gen' => 18,'created_at' => now()],
            ['nrp' => 'M2101006','name' => 'Komala Wahyu Artha Mulya','class' => 'XI.U.S-3','division' => 'MM','gen' => 18,'created_at' => now()],
            ['nrp' => 'M2101008','name' => 'Panji Murti Wibowo ','class' => 'XI.U.A-1','division' => 'MM','gen' => 18,'created_at' => now()],
            ['nrp' => 'M2101009','name' => 'Putri Fachira Selima ','class' => 'XI.U.S-3','division' => 'MM','gen' => 18,'created_at' => now()],
            ['nrp' => 'M2101010','name' => 'Rafael Bryan Grizalle Silaban ','class' => 'XI.IPA-1','division' => 'MM','gen' => 18,'created_at' => now()],
            ['nrp' => 'M2101011','name' => 'Raihan Rahmandika Putra Iskandar','class' => 'XI.IPA-3','division' => 'MM','gen' => 18,'created_at' => now()],
            ['nrp' => 'M2101012','name' => 'Raindri Manheris','class' => 'XI.U.S-1','division' => 'MM','gen' => 18,'created_at' => now()],
            ['nrp' => 'M2101013','name' => 'Siti Fadhilah Nur Nisrina ','class' => 'XI.IPA-3','division' => 'MM','gen' => 18,'created_at' => now()],
            ['nrp' => 'M2101014','name' => 'Talita Azmi Ophelia ','class' => 'XI.U.S-2','division' => 'MM','gen' => 18,'created_at' => now()],
            ['nrp' => 'M2101015','name' => 'Tasya Adelia Ramadhani ','class' => 'XI.IPA-5','division' => 'MM','gen' => 18,'created_at' => now()],
            ['nrp' => 'M2101016','name' => 'Tyas Nur Azalia ','class' => 'XI.IPA-3','division' => 'MM','gen' => 18,'created_at' => now()],
            ['nrp' => 'M2211003','name' => 'Azzahra Tsaabitah Dhiya Ulhaq','class' => 'X.IPA-1','division' => 'MM','gen' => 19,'created_at' => now()],
            ['nrp' => 'M2211005','name' => 'Chaerunnisa Shafarani','class' => 'X.IPA-1','division' => 'MM','gen' => 19,'created_at' => now()],
            ['nrp' => 'M2211006','name' => 'Damar Dydan Aryapandya Suprpato','class' => 'X.IPA-2','division' => 'MM','gen' => 19,'created_at' => now()],
            ['nrp' => 'M2211007','name' => 'Dhania Aisyah Putri Prasojo','class' => 'X.U.S-2','division' => 'MM','gen' => 19,'created_at' => now()],
            ['nrp' => 'M2211008','name' => 'Dhica Cynthia Putri Kinanti Mahira','class' => 'X.U.A-5','division' => 'MM','gen' => 19,'created_at' => now()],
            ['nrp' => 'M2211009','name' => 'Diah Marlina','class' => 'X.IPA-2','division' => 'MM','gen' => 19,'created_at' => now()],
            ['nrp' => 'M2211010','name' => 'Djayanti Prabowo','class' => 'X.IPA-3','division' => 'MM','gen' => 19,'created_at' => now()],
            ['nrp' => 'M2211011','name' => 'Esa Putri Ramadhani','class' => 'X.IPA-1','division' => 'MM','gen' => 19,'created_at' => now()],
            ['nrp' => 'M2211012','name' => 'Farrel Colbert Kayleen','class' => 'X.U.A-6','division' => 'MM','gen' => 19,'created_at' => now()],
            ['nrp' => 'M2211013','name' => 'Farrell Raffi Dwidee','class' => 'X.U.A-4','division' => 'MM','gen' => 19,'created_at' => now()],
            ['nrp' => 'M2211014','name' => 'Fauzan Nur Fadly Ilham','class' => 'X.U.A-1','division' => 'MM','gen' => 19,'created_at' => now()],
            ['nrp' => 'M2211015','name' => 'Fayyaza Parsa Helaw','class' => 'X.U.A-6','division' => 'MM','gen' => 19,'created_at' => now()],
            ['nrp' => 'M2211016','name' => 'Franjeris Langlang Buwono','class' => 'X.U.A-5','division' => 'MM','gen' => 19,'created_at' => now()],
            ['nrp' => 'M2211018','name' => 'Hilmiy Sahlan Ramadhan','class' => 'X.U.A-4','division' => 'MM','gen' => 19,'created_at' => now()],
            ['nrp' => 'M2211019','name' => 'Khaila Hasra Munaya','class' => 'X.IPA-1','division' => 'MM','gen' => 19,'created_at' => now()],
            ['nrp' => 'M2211021','name' => 'M Ghalih R','class' => 'X.U.A-1','division' => 'MM','gen' => 19,'created_at' => now()],
            ['nrp' => 'M2211022','name' => 'Muhamad Afwan Imam Nasuha','class' => 'X.IPA-3','division' => 'MM','gen' => 19,'created_at' => now()],
            ['nrp' => 'M2211023','name' => 'Muhamad Indra Wahyu Pradana','class' => 'X.U.A-5','division' => 'MM','gen' => 19,'created_at' => now()],
            ['nrp' => 'M2211024','name' => 'Muhammad Ali Akbar Almansur','class' => 'X.P.A-1','division' => 'MM','gen' => 19,'created_at' => now()],
            ['nrp' => 'M2211025','name' => 'Muhammad Arsya Al-Zahran','class' => 'X.U.A-4','division' => 'MM','gen' => 19,'created_at' => now()],
            ['nrp' => 'M2211026','name' => 'Muhammad Daffa Valentino','class' => 'X.U.S-2','division' => 'MM','gen' => 19,'created_at' => now()],
            ['nrp' => 'M2211028','name' => 'Muhammad Ramadhan Putra Balya','class' => 'X.P.A-1','division' => 'MM','gen' => 19,'created_at' => now()],
            ['nrp' => 'M2211029','name' => 'Nadhin Galuh Ekania Wijanarko','class' => 'X.IPA-5','division' => 'MM','gen' => 19,'created_at' => now()],
            ['nrp' => 'M2211030','name' => 'Nadia Fransiska Sari','class' => 'X.U.A-1','division' => 'MM','gen' => 19,'created_at' => now()],
            ['nrp' => 'M2211031','name' => 'Nafisha Belva Azalia','class' => 'X.U.A-1','division' => 'MM','gen' => 19,'created_at' => now()],
            ['nrp' => 'M2211032','name' => 'Ragil Bagus Fabian','class' => 'X.IPA-5','division' => 'MM','gen' => 19,'created_at' => now()],
            ['nrp' => 'M2211033','name' => 'Retno Setiawati','class' => 'X-IPS-2','division' => 'MM','gen' => 19,'created_at' => now()],
            ['nrp' => 'M2211034','name' => 'Rikaz Sinatra Mumtaz','class' => 'X.U.A-4','division' => 'MM','gen' => 19,'created_at' => now()],
            ['nrp' => 'M2211035','name' => 'Rina Yunihariyanti','class' => 'X.IPA-4','division' => 'MM','gen' => 19,'created_at' => now()],
            ['nrp' => 'M2211036','name' => 'Sabillah Puti Amalia','class' => 'X.U.S-2','division' => 'MM','gen' => 19,'created_at' => now()],
            ['nrp' => 'M2211037','name' => 'Safina Putri Marianti','class' => 'X.U.S-2','division' => 'MM','gen' => 19,'created_at' => now()],
            ['nrp' => 'M2211038','name' => 'Syauqina Sri Izzati','class' => 'X.U.S-2','division' => 'MM','gen' => 19,'created_at' => now()],
            ['nrp' => 'M2211039','name' => 'Windi Rahayu','class' => 'X.IPA-2','division' => 'MM','gen' => 19,'created_at' => now()],
            ['nrp' => 'M2211040','name' => 'Afrida Dwi Azzahra','class' => 'X.U.A-3','division' => 'MM','gen' => 19,'created_at' => now()],
            ['nrp' => 'M2211041','name' => 'Kansathabina Anindita','class' => 'X.U.S-1','division' => 'MM','gen' => 19,'created_at' => now()],
            ['nrp' => 'M2211042','name' => 'Nakhla Syahda Ramadhani','class' => 'X.IPA-2','division' => 'MM','gen' => 19,'created_at' => now()],
            ['nrp' => 'M2211045','name' => 'Nur Syifa Herdiyanti','class' => 'X.U.A-1','division' => 'MM','gen' => 19,'created_at' => now()],
            ['nrp' => 'M2211044','name' => "Q'nan Khalifi Rahmadanty",'class' => 'X.IPA-2','division' => 'MM','gen' => 19,'created_at' => now()],
            ['nrp' => 'R2211001','name' => 'Abang Muhammad Idris','class' => 'X.P.A-1','division' => 'RPL','gen' => 19,'created_at' => now()],
            ['nrp' => 'R2211002','name' => 'Akbar Henritama Prasetyo','class' => 'X.U.A-4','division' => 'RPL','gen' => 19,'created_at' => now()],
            ['nrp' => 'R2211003','name' => 'Akhtar Maulana Albani','class' => 'X.U.A-3','division' => 'RPL','gen' => 19,'created_at' => now()],
            ['nrp' => 'R2211004','name' => 'Amelia Nurbaeti','class' => 'X.IPA-4','division' => 'RPL','gen' => 19,'created_at' => now()],
            ['nrp' => 'R2211005','name' => 'Ayudhina Nilamsari','class' => 'X.IPA-4','division' => 'RPL','gen' => 19,'created_at' => now()],
            ['nrp' => 'R2211006','name' => 'Bagus Satria Adiguna','class' => 'X.P.A-1','division' => 'RPL','gen' => 19,'created_at' => now()],
            ['nrp' => 'R2211032','name' => 'Barkach Yoni Wibowo','class' => 'X.U.A-3','division' => 'RPL','gen' => 19,'created_at' => now()],
            ['nrp' => 'R2211007','name' => 'Billal Aidan Nehan','class' => 'X.U.A-1','division' => 'RPL','gen' => 19,'created_at' => now()],
            ['nrp' => 'R2211008','name' => 'Bradstern Haychael Alfath Saputra','class' => 'X.U.A-5','division' => 'RPL','gen' => 19,'created_at' => now()],
            ['nrp' => 'R2211009','name' => 'Darren Rahadian Jati Pamungkas','class' => 'X.IPA-3','division' => 'RPL','gen' => 19,'created_at' => now()],
            ['nrp' => 'R2211010','name' => 'Delia Febriana','class' => 'X.IPA-2','division' => 'RPL','gen' => 19,'created_at' => now()],
            ['nrp' => 'R2101003','name' => 'Devin Reynar','class' => 'XI.IPA-2','division' => 'RPL','gen' => 18,'created_at' => now()],
            ['nrp' => 'R2211011','name' => 'Falih Muhammad Altaf','class' => 'X.U.A-3','division' => 'RPL','gen' => 19,'created_at' => now()],
            ['nrp' => 'R2211013','name' => 'Ghiyas Hafizh Pujadi','class' => 'X.U.A-2','division' => 'RPL','gen' => 19,'created_at' => now()],
            ['nrp' => 'R2211014','name' => 'Gibran Subardi','class' => 'X.IPA-3','division' => 'RPL','gen' => 19,'created_at' => now()],
            ['nrp' => 'R2211015','name' => 'Indriani Nusa Bakti','class' => 'X.U.A-3','division' => 'RPL','gen' => 19,'created_at' => now()],
            ['nrp' => 'R2101005','name' => 'Jamal Arjuna Dwi Ridwansyah','class' => 'XI.U.A-2','division' => 'RPL','gen' => 18,'created_at' => now()],
            ['nrp' => 'R2211031','name' => 'Kezia Adelia Martin','class' => 'X.U.S-2','division' => 'RPL','gen' => 19,'created_at' => now()],
            ['nrp' => 'R2211016','name' => 'Kian Syachbi Delano Roosevelt','class' => 'X.IPA-5','division' => 'RPL','gen' => 19,'created_at' => now()],
            ['nrp' => 'R2211017','name' => 'Moch Fahmi Bima Pambudi','class' => 'X.IPA-4','division' => 'RPL','gen' => 19,'created_at' => now()],
            ['nrp' => 'R2211018','name' => 'Mochamad Nur Avandi','class' => 'X.IPA-5','division' => 'RPL','gen' => 19,'created_at' => now()],
            ['nrp' => 'R2211019','name' => 'Mohammad Zindan Ramadhan','class' => 'X.IPA-1','division' => 'RPL','gen' => 19,'created_at' => now()],
            ['nrp' => 'R2211020','name' => 'Muhammad Afthar Fathiandra','class' => 'X.P.A-1','division' => 'RPL','gen' => 19,'created_at' => now()],
            ['nrp' => 'R2101007','name' => 'Muhammad Afzal Faizi','class' => 'XI.U.A-2','division' => 'RPL','gen' => 18,'created_at' => now()],
            ['nrp' => 'R2211021','name' => 'Muhammad Luthfi karunia wijaya','class' => 'X.P.A-1','division' => 'RPL','gen' => 19,'created_at' => now()],
            ['nrp' => 'R2101008','name' => 'Nabil Eka Satria Ari Firmansyah','class' => 'XI.U.A-2','division' => 'RPL','gen' => 18,'created_at' => now()],
            ['nrp' => 'R2211023','name' => 'Naufal Fatihul Rizky','class' => 'X.IPA-5','division' => 'RPL','gen' => 19,'created_at' => now()],
            ['nrp' => 'R2101010','name' => 'Nazkia Najidah Ramdani','class' => 'XI.P.A-1','division' => 'RPL','gen' => 18,'created_at' => now()],
            ['nrp' => 'R2211024','name' => 'Ni Wayan Arghi Putri Irawan','class' => 'X.U.A-4','division' => 'RPL','gen' => 19,'created_at' => now()],
            ['nrp' => 'R2101011','name' => 'Nurmala Setya Ningrum','class' => 'XI.IPA-3','division' => 'RPL','gen' => 18,'created_at' => now()],
            ['nrp' => 'R2101012','name' => 'Otniel Anggi Arauna Batubara','class' => 'XI.P.A-1','division' => 'RPL','gen' => 18,'created_at' => now()],
            ['nrp' => 'R2211025','name' => 'Puji Rahayu Andryansah','class' => 'X.U.A-5','division' => 'RPL','gen' => 19,'created_at' => now()],
            ['nrp' => 'R2211026','name' => 'Putra Dwi Wicaksono','class' => 'X.U.A-4','division' => 'RPL','gen' => 19,'created_at' => now()],
            ['nrp' => 'R2211027','name' => 'Rafi Ibrahim Ahmad Naufal','class' => 'X.U.A-3','division' => 'RPL','gen' => 19,'created_at' => now()],
            ['nrp' => 'R2211028','name' => 'Razan Afif Maheswara','class' => 'X.U.A-2','division' => 'RPL','gen' => 19,'created_at' => now()],
            ['nrp' => 'R2211029','name' => 'Reza Zainal Abidin','class' => 'X.IPA-2','division' => 'RPL','gen' => 19,'created_at' => now()],
            ['nrp' => 'R2101014','name' => 'Valentinus Moreno','class' => 'XI IPA 4','division' => 'RPL','gen' => 18,'created_at' => now()],
            ['nrp' => 'R2101015','name' => 'Vincentius Andriell','class' => 'XI.P.A-1','division' => 'RPL','gen' => 18,'created_at' => now()],
            ['nrp' => 'R2101016','name' => 'Zidane Triyano Anggoro','class' => 'XI.IPA-4','division' => 'RPL','gen' => 18,'created_at' => now()],
            ['nrp' => 'T2211001','name' => 'Elisabeth Damaris Fingkreuw','class' => 'X.IPS-1','division' => 'TKJ','gen' => 19,'created_at' => now()],
            ['nrp' => 'T2101002','name' => 'Febriyana Endah','class' => 'XI.U.S-2','division' => 'TKJ','gen' => 18,'created_at' => now()],
            ['nrp' => 'T2211003','name' => 'Izdihar Al Khasyi','class' => 'X.U.A-3','division' => 'TKJ','gen' => 19,'created_at' => now()],
            ['nrp' => 'T2211005','name' => 'Mila Diya','class' => 'X.U.A-3','division' => 'TKJ','gen' => 19,'created_at' => now()],
            ['nrp' => 'T2211004','name' => 'Java Julio Handono','class' => 'XI.IPA-3','division' => 'TKJ','gen' => 18,'created_at' => now()],
            ['nrp' => 'T2101006','name' => 'Muhammad Yustiar Soyaharja','class' => 'XI.IPA-5','division' => 'TKJ','gen' => 18,'created_at' => now()],
            ['nrp' => 'T2211008','name' => 'Nazwa Nurrahmah','class' => 'X.IPS-3','division' => 'TKJ','gen' => 19,'created_at' => now()],
            ['nrp' => 'T2211014','name' => 'Nazwa Puji Julianti','class' => 'X.IPS-1','division' => 'TKJ','gen' => 19,'created_at' => now()],
            ['nrp' => 'M2211017','name' => 'Gisella Tithania Anhabel','class' => 'X.IPA-5','division' => 'TKJ','gen' => 19,'created_at' => now()],
            ['nrp' => 'T2211011','name' => 'Ratu Balqis ','class' => 'X.IPA-2','division' => 'TKJ','gen' => 19,'created_at' => now()],
            ['nrp' => 'T2211012','name' => 'Septian Tjuelfi Annajmi','class' => 'X.IPS-2','division' => 'TKJ','gen' => 19,'created_at' => now()],
            ['nrp' => 'T2101004','name' => 'Shafira Azzahra Tamimi','class' => 'XI.U.S-2','division' => 'TKJ','gen' => 18,'created_at' => now()],
            ['nrp' => 'T2211013','name' => 'Sutan Fajri Ramadhan','class' => 'X.IPA-2','division' => 'TKJ','gen' => 19,'created_at' => now()],
            ['nrp' => 'T2101005','name' => 'Yoshimura Abimanyu','class' => 'XI.U.A-4','division' => 'TKJ','gen' => 18,'created_at' => now()],
        ];

        DB::table('students')->insert($data);
    }
}
